version: '3.8'
services:
  web:
    build: .
    ports: ['8000:8000']
    env_file: .env
    volumes: ['.:/app']
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: jblb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Newbie@1994
    ports: ['5433:5432']
